# Generated by Django 5.2.12 on 2026-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=200)),
                ('class_time_in', models.TimeField()),
                ('class_time_out', models.TimeField()),
                ('class_schedule', models.CharField(choices=[('mtw', 'Monday to Wednesday'), ('thfs', 'Thursday to Saturday')], max_length=10)),
                ('class_code', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('attendance_file', models.FileField(blank=True, null=True, upload_to='attendance/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['class_time_in'],
            },
        ),
    ]
