# Generated by Django 5.2.12 on 2026-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=200)),
                ('class_time_in', models.TimeField()),
                ('class_time_out', models.TimeField()),
                ('class_schedule', models.CharField(choices=[('mon-wed', 'Monday to Wednesday'), ('thur-sat', 'Thursday to Saturday')], max_length=20)),
                ('class_code', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('official', 'Official'), ('tentative', 'Tentative')], default='tentative', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['class_time_in'],
            },
        ),
    ]
