# Generated by Django 5.2.12 on 2026-03-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=200)),
                ('class_code', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=200)),
                ('date_filed', models.DateField()),
                ('date_of_use', models.DateField()),
                ('room_num', models.CharField(max_length=50)),
                ('date_of_return', models.DateField()),
                ('course', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('unapproved', 'Unapproved'), ('approved', 'Approved')], default='unapproved', max_length=20)),
                ('class_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='reservation.reservation')),
            ],
        ),
    ]
