# Generated by Django 5.2.12 on 2026-03-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='class_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
