# Generated by Django 5.2.12 on 2026-03-08 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('present', 'Present'), ('absent', 'Absent')], default='pending', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='schedule.schedule')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
    ]
