# Generated by Django 5.2.12 on 2026-03-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lab', models.CharField(choices=[('physics', 'Physics'), ('biology', 'Biology'), ('civil', 'Civil'), ('chemistry', 'Chemistry'), ('culinary', 'Culinary'), ('electrical', 'Electrical'), ('mechanical', 'Mechanical'), ('hydraulic', 'Hydraulic')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
                ('available_quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
